//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int Id { get; set; }
        public Nullable<int> Musteri_Kodu { get; set; }
        public string Musteri_Ad { get; set; }
        public string Musteri_Soyad { get; set; }
        public string Musteri_Telefon { get; set; }
        public string Musteri_Adres { get; set; }
        public string Musteri_Vd { get; set; }
        public string Musteri_Vkn_Tc { get; set; }
        public string Musteri_Aciklama { get; set; }
        public Nullable<double> Musteri_Bakiye { get; set; }
        public string Kullanici { get; set; }
    }
}
